[
build
]
  command = "if cd flutter; then git pull; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter build web --release"
  publish = "build/web"

[
build.environment
]
  FLUTTER_VERSION = "stable"

[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200