[build]
  command = """
    rm -rf flutter && \
    git clone https://github.com/flutter/flutter.git --depth 1 --branch stable && \
    export PATH="$PATH:`pwd`/flutter/bin" && \
    flutter doctor && \
    flutter config --enable-web && \
    flutter build web --release && \
    sed -i "s/{{GROQ_API_KEY}}/$GROQ_API_KEY/g" build/web/index.html
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  FLUTTER_VERSION = "stable"